#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.




menuentry "Fedora 38 ISO / Xfce" --class Fedora {
	set iso_file="/opt/iso/fedora/38/Fedora-Xfce-Live-x86_64-38-1.6.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/images/pxeboot/vmlinuz iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-Xfce-Live-38-1-6 rd.live.image rhgb $boot_option
	initrd (loop)/images/pxeboot/initrd.img
}
