#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.




menuentry "Fedora 43 ISO / Gnome Shell (Workstation)" --class fedora {
	set iso_file="/opt/iso/fedora/43/Fedora-Workstation-Live-43-1.6.x86_64.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/boot/x86_64/loader/linux iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-WS-Live-43 rd.live.image rhgb $boot_option
	initrd (loop)/boot/x86_64/loader/initrd
}




menuentry "Fedora 43 ISO / Kde Plasma" --class fedora {
	set iso_file="/opt/iso/fedora/43/Fedora-KDE-Desktop-Live-43-1.6.x86_64.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/boot/x86_64/loader/linux iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-KDE-Live-43 rd.live.image rhgb $boot_option
	initrd (loop)/boot/x86_64/loader/initrd
}




menuentry "Fedora 43 ISO / Xfce" --class fedora {
	set iso_file="/opt/iso/fedora/43/Fedora-Xfce-Live-43-1.6.x86_64.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/boot/x86_64/loader/linux iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-Xfce-Live-43 rd.live.image rhgb $boot_option
	initrd (loop)/boot/x86_64/loader/initrd
}




menuentry "Fedora 43 ISO / Lxqt" --class fedora {
	set iso_file="/opt/iso/fedora/43/Fedora-LXQt-Live-43-1.6.x86_64.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/boot/x86_64/loader/linux iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-LXQt-Live-43 rd.live.image rhgb $boot_option
	initrd (loop)/boot/x86_64/loader/initrd
}




menuentry "Fedora 43 ISO / Lxde" --class fedora {
	set iso_file="/opt/iso/fedora/43/Fedora-LXDE-Live-x86_64-43-1.6.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/boot/x86_64/loader/linux iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-LXDE-Live-43-1-1 rd.live.image rhgb $boot_option
	initrd (loop)/boot/x86_64/loader/initrd
}




menuentry "Fedora 43 ISO / Budgie" --class fedora {
	set iso_file="/opt/iso/fedora/43/Fedora-Budgie-Live-43-1.6.x86_64.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/boot/x86_64/loader/linux iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-Budgie-Live-43 rd.live.image rhgb $boot_option
	initrd (loop)/boot/x86_64/loader/initrd
}




menuentry "Fedora 43 ISO / Mate Compiz" --class fedora {
	set iso_file="/opt/iso/fedora/43/Fedora-MATE_Compiz-Live-x86_64-43-1.6.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/boot/x86_64/loader/linux iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-MATE-Live-43-1-1 rd.live.image rhgb $boot_option
	initrd (loop)/boot/x86_64/loader/initrd
}




menuentry "Fedora 43 ISO / Cinnamon" --class fedora {
	set iso_file="/opt/iso/fedora/43/Fedora-Cinnamon-Live-x86_64-43-1.6.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/boot/x86_64/loader/linux iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-Cinn-Live-43-1-1 rd.live.image rhgb $boot_option
	initrd (loop)/boot/x86_64/loader/initrd
}




menuentry "Fedora 43 ISO / Cosmic" --class fedora {
	set iso_file="/opt/iso/fedora/43/Fedora-COSMIC-Live-43-1.6.x86_64.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/boot/x86_64/loader/linux iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-CSMC-Live-43 rd.live.image rhgb $boot_option
	initrd (loop)/boot/x86_64/loader/initrd
}




menuentry "Fedora 43 ISO / I3" --class fedora {
	set iso_file="/opt/iso/fedora/43/Fedora-i3-Live-x86_64-43-1.6.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/boot/x86_64/loader/linux iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-i3-Live-43-1-1 rd.live.image rhgb $boot_option
	initrd (loop)/boot/x86_64/loader/initrd
}




menuentry "Fedora 43 ISO / Sway" --class fedora {
	set iso_file="/opt/iso/fedora/43/Fedora-Sway-Live-x86_64-43-1.6.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/boot/x86_64/loader/linux iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-Sway-Live-43-1-1 rd.live.image rhgb $boot_option
	initrd (loop)/boot/x86_64/loader/initrd
}




menuentry "Fedora 43 ISO / MiracleWM" --class fedora {
	set iso_file="/opt/iso/fedora/43/Fedora-MiracleWM-Live-43-1.6.x86_64.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/boot/x86_64/loader/linux iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-MirWM-Live-43 rd.live.image rhgb $boot_option
	initrd (loop)/boot/x86_64/loader/initrd
}




menuentry "Fedora 43 ISO / SoaS" --class fedora {
	set iso_file="/opt/iso/fedora/43/Fedora-SoaS-Live-43-1.6.x86_64.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/boot/x86_64/loader/linux iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-SoaS-Live-43 rd.live.image rhgb $boot_option
	initrd (loop)/boot/x86_64/loader/initrd
}




menuentry "Fedora 43 ISO / Kde Mobile" --class fedora {
	set iso_file="/opt/iso/fedora/43/Fedora-KDE-Mobile-Live-43-1.6.x86_64.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	set boot_option=""
	#set boot_option="quiet splash"
	linux (loop)/boot/x86_64/loader/linux iso-scan/filename=$iso_file root=live:CDLABEL=Fedora-KDEM-Live-43 rd.live.image rhgb $boot_option
	initrd (loop)/boot/x86_64/loader/initrd
}
